#include "token.h"

using namespace std;

std::string TokenTypeToString(TokenType type) {
    switch (type) {
    case TokenType::ILLEGAL:
        return "ILLEGAL";
    case TokenType::END_OF_FILE:
        return "END_OF_FILE";
    case TokenType::NEW_LINE:
        return "NEW_LINE";
    case TokenType::SPACE:
        return "SPACE";
    case TokenType::TAB:
        return "TAB";
    case TokenType::IDENTIFIER:
        return "IDENTIFIER";
    case TokenType::INTEGER:
        return "INTEGER";
    case TokenType::FLOAT:
        return "FLOAT";
    case TokenType::STRING:
        return "STRING";
    case TokenType::PLUS:
        return "PLUS";
    case TokenType::MINUS:
        return "MINUS";
    case TokenType::ASTERISK:
        return "ASTERISK";
    case TokenType::SLASH:
        return "SLASH";
    case TokenType::PERCENT:
        return "PERCENT";
    case TokenType::ASSIGN:
        return "ASSIGN";
    case TokenType::EQUAL:
        return "EQUAL";
    case TokenType::NOT_EQUAL:
        return "NOT_EQUAL";
    case TokenType::PLUS_ASSIGN:
        return "PLUS_ASSIGN";
    case TokenType::MINUS_ASSIGN:
        return "MINUS_ASSIGN";
    case TokenType::ASTERISK_ASSIGN:
        return "ASTERISK_ASSIGN";
    case TokenType::SLASH_ASSIGN:
        return "SLASH_ASSIGN";
    case TokenType::PERCENT_ASSIGN:
        return "PERCENT_ASSIGN";
    case TokenType::LPAREN:
        return "LPAREN";
    case TokenType::RPAREN:
        return "RPAREN";
    case TokenType::LBRACE:
        return "LBRACE";
    case TokenType::RBRACE:
        return "RBRACE";
    case TokenType::LBRACKET:
        return "LBRACKET";
    case TokenType::RBRACKET:
        return "RBRACKET";
    case TokenType::COLON:
        return "COLON";
    case TokenType::SEMICOLON:
        return "SEMICOLON";
    case TokenType::정수:
        return "정수";
    case TokenType::실수:
        return "실수";
    case TokenType::문자:
        return "문자";
    case TokenType::리턴:
        return "리턴";
    case TokenType::만약:
        return "만약";
    case TokenType::라면:
        return "라면";
    case TokenType::아니면:
        return "아니면";
    case TokenType::함수:
        return "함수";
    case TokenType::TRUE:
        return "TRUE";
    case TokenType::FALSE:
        return "FALSE";
    case TokenType::반복:
        return "반복";
    case TokenType::동안:
        return "동안";
    case TokenType::중단:
        return "중단";
    case TokenType::계속:
        return "계속";
    case TokenType::논리:
        return "논리";
    case TokenType::배열:
        return "배열";
    case TokenType::사전:
        return "사전";
    case TokenType::가져오기:
        return "가져오기";
    case TokenType::없음:
        return "없음";
    case TokenType::비교:
        return "비교";
    case TokenType::경우:
        return "경우";
    case TokenType::기본:
        return "기본";
    case TokenType::클래스:
        return "클래스";
    case TokenType::생성:
        return "생성";
    case TokenType::자기:
        return "자기";
    case TokenType::부모:
        return "부모";
    case TokenType::부터:
        return "부터";
    case TokenType::까지:
        return "까지";
    case TokenType::각각:
        return "각각";
    case TokenType::에서:
        return "에서";
    case TokenType::시도:
        return "시도";
    case TokenType::실패:
        return "실패";
    case TokenType::BITWISE_AND:
        return "BITWISE_AND";
    case TokenType::LOGICAL_AND:
        return "LOGICAL_AND";
    case TokenType::BITWISE_OR:
        return "BITWISE_OR";
    case TokenType::LOGICAL_OR:
        return "LOGICAL_OR";
    case TokenType::COMMA:
        return "COMMA";
    case TokenType::RIGHT_ARROW:
        return "RIGHT_ARROW";
    case TokenType::START_BLOCK:
        return "START_BLOCK";
    case TokenType::END_BLOCK:
        return "END_BLOCK";
    case TokenType::BANG:
        return "BANG";
    case TokenType::LESS_THAN:
        return "LESS_THAN";
    case TokenType::GREATER_THAN:
        return "GREATER_THAN";
    case TokenType::LESS_EQUAL:
        return "LESS_EQUAL";
    case TokenType::GREATER_EQUAL:
        return "GREATER_EQUAL";
    case TokenType::DOT:
        return "DOT";
    case TokenType::ELLIPSIS:
        return "ELLIPSIS";

    default:
        break;
    }
    return "UNKNOWN";
}
